# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    ConnectedServiceName: 'VMDeploymentService'
    deploymentScope: 'Resource Group'
    subscriptionId: 'ec765027-1f12-4615-a2fc-1a3a9f44cda2'
    resourceGroupName: 'template'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/patrikas-sestokas/AzureARMTemplate/main/VMtest.json'
    # csmParametersFileLink: 'https://raw.githubusercontent.com/patrikas-sestokas/AzureARMTemplate/main/template/parameters.json'
